export * as Header from './Header'
export { HomeHero } from './HomeHero'
export { FeaturedProperties } from './FeaturedProperties'
export { OurServices } from './OurServices'
export { Instagram } from './Instagram'
export { Footer } from './Footer'
